### ISSUE TITLE
MODIFY event gets missed

### ISSUE THREAD

**Issue by arrowd** [libinotify-kqueue/libinotify-kqueue#10]
I run `inotify-test` on an empty folder. After that, I run the following code:

```
#include <QFile>

void createFile(const QString &path)
{
    QFile file(path);
    file.open(QIODevice::WriteOnly);
    file.write(QByteArray("foo"));
    file.close();
    //qDebug() << path;
}

int main()
{
    createFile("test/file");
    return 0;
}
```

which boils down to

```
openat(AT_FDCWD,"test/file",O_WRONLY|O_CREAT|O_TRUNC|O_CLOEXEC,0666) = 3 (0x3)
fstat(3,{ mode=-rw-r--r-- ,inode=1513712,size=0,blksize=131072 }) = 0 (0x0)
write(3,"foo",3)                                 = 3 (0x3)
close(3)  
```

The `inotify-test` output after that is following:

> file created in watched directory [file]
> file opened for writing was closed [file]

which corresponds to `IN_CREATE` and `IN_CLOSE_WRITE` events.

However, on Linux `IN_MODIFY` is also emitted, which seems pretty logical.

**Comment by wulf7** [comment]
Could you retest after adding a small (e.g. 1ms) delay in between open() and write() to testcase?

**Comment by arrowd** [comment]
Indeed, adding `QThread::msleep(1);` before the write makes inotify report

> file was modified [file]

Can anything be done to fix this properly?

**Comment by wulf7** [comment]
> Indeed, adding `QThread::msleep(1);` before the write makes inotify report

Than this is ordinary race between monitored writer and monitoring thread. libinotify have to perform readdir() -> open() -> kevent() chain of calls before freshly created subfile get watched. If your code wins the race against libinotify worker, than your events are lost.

> Can anything be done to fix this properly?

IMO, nothing. You can't close this window. You must always perform open() and kevent() before file get watched. It is possible to add some heuristics based e.g. on file birthtime and size to track recent writes but it can results in false events e.g. if file was created in other directory and than was promptly moved to watched directory.

**Comment by arrowd** [comment]
Okay, thanks for explanations.
