### ISSUE TITLE
Can you provide a pkg-config file?

### ISSUE THREAD

**Issue by dcdowse** [libinotify-kqueue/libinotify-kqueue#2]
Please put a file for pkg-config in your repo 

/usr/local/libdata/pkg-config/libinotify.pc

`prefix=/usr/local`
`exec_prefix=${prefix}`
`libdir=${exec_prefix}/lib`
`includedir=${prefix}/include`

`Name: libinotify`
`Description: Kevent base inotify compatible library`
`Version: 20160505`
`Libs: -L${libdir} -linotify`
`Cflags: -I${includedir}`

I came across this while working on https://github.com/jaagr/polybar and fixing build errors on FreeBSD

BTW. I am new to git and also into coding so please forgive me if this is not the correct way to handle stuff on git. 
I'm still deep in the learning process of git & github

**Comment by wulf7** [comment]
Are you sure that pkg-config file helps to build any inotify-dependent software? In Linux inotify is not library but kernel service exported via libc, so usually configure scripts do not try query pkg-config for compiling or linking options, rather they just check sys/inotify.h header for existence.
Basically, I`m not object to place this file in repo and install it along with library itself. I am just wondering if it has any sense?

**Comment by dcdowse** [comment]
Isn't that whole pkg-config thing about to make it easier to link libs and all? But i do also not really care if you want or not to include a file to make build linux software easier on freebsd. Those 10 ppl who do build linux software from git will figure it out by themself how to make cmake get the right libs to build with your port.

**Comment by wulf7** [comment]
> Isn't that whole pkg-config thing about to make it easier to link libs and all? But i do also not really care if you want or not to include a file to make build linux software easier on freebsd.

I have not seen software querying pkg-config for inotify support yet. If you going to be the first man who wrote such a one, go ahead:
I pushed support for pkg-config in my own repo: https://github.com/wulf7/libinotify-kqueue.git
It only compile/install tested and installs .pc in **/usr/local/lib/pkg-config**, not /usr/local/libdata/pkg-config so it is up to you to patch sources locally to set the right place (e.g. you can add USES+=pathfix to FreeBSD port Makefile).
If it would solve build errors for you I would push changes upstream.

**Comment by wulf7** [comment]
Nevertheless, I see no way installing .pc file can hurt so I will include this change on next libinotify update.

Thank you for contribution!

**Comment by dcdowse** [comment]
That's nice, thank you.

**Comment by v00d00** [comment]
Any news?

**Comment by wulf7** [comment]
I`m going to upstream next part of changes within 2 or 3 weeks. If someone`s work depends on pkg-config file, just notify me. I will push it ASAP.

**Comment by wulf7** [comment]
Finally, upstreamed
