### ISSUE TITLE
"Bad system call" when using with dotnet

### ISSUE THREAD

**Issue by Warafreak** [libinotify-kqueue/libinotify-kqueue#20]
I have encountered a peculiar error when using this library in conjunction with the dotnet binaries for FreeBSD 13.

Whenever I try to update my version of `libinotify` from version `20211018_1` to version `20240724` through pkg, my dotnet applications fail to start.

I have isolated this issue to some conflict between `dotnet` and `libinotify` and have not yet found any solution to getting them working together.

Is this a known issue? Could I assist you in some way with the debugging?

**Comment by wulf7** [comment]
Most probably your userworld is newer than kernel. libinotify in 20240724 started to use kqueuex() instead of kqueue() if it is available at build time.
So just update your kernel or rebuild libinotify with kqueuex disabled.

**Comment by Warafreak** [comment]
Sorry for the late reply.
After getting around to updating the underlying host systems kernel to FreeBSD 13.3 this issue was solved. 
Thanks for the quick help.
