### ISSUE TITLE
Error building on 32-bit powerpc

### ISSUE THREAD

**Issue by chmeeedalf** [libinotify-kqueue/libinotify-kqueue#4]
Building libinotify for 32-bit powerpc shows the following error:

libtool: compile:  cc -DHAVE_CONFIG_H -I. -I. -DNDEBUG -D_THREAD_SAFE -pthread -Wall -Werror -O2 -pipe -fno-strict-aliasing -MT libinotify_la-worker-thread.lo -MD -M
P -MF .deps/libinotify_la-worker-thread.Tpo -c worker-thread.c  -fPIC -DPIC -o .libs/libinotify_la-worker-thread.o
cc1: warnings being treated as errors
worker-thread.c: In function 'worker_thread':
worker-thread.c:533: warning: cast to pointer from integer of different size

kevent->data is type __int64_t, casting to a 32-bit pointer.

**Comment by wulf7** [comment]
Line 533 of worker-thread.c probably should look like
`cmd = (worker_cmd *)(uintptr_t)received[i].data;`
I will have opportunities to check this after returning from my vacations (~ in one week)

**Comment by wulf7** [comment]
You can test release candidate for the upcoming release: https://github.com/wulf7/libinotify-kqueue

**Comment by chmeeedalf** [comment]
Latest snapshot builds fine on my 32-bit powerpc machine.  Thanks!

**Comment by chmeeedalf** [comment]
Fixed by 0b955eede2c635b425d56fc5f549b417f899dcdc
